### ISSUE TITLE
[BUG] 配對會報錯，但是不知道錯誤是什麼

### ISSUE THREAD

**Issue by Avi-python** [csie-software-engineering/resonance-chatroom#86]
## 錯誤說明

這個錯誤是由 _pairOrWait 報出的

## 預期結果

可以成功配對

## 圖片或影片

![image](https://github.com/csie-software-engineering/resonance-chatroom/assets/62063088/30fd7b85-c364-43b6-9610-90ad35165180)

## 關聯 ISSUE

* #50 
* #70

**Comment by garyellow** [comment]
#87
