### ISSUE TITLE
[BUG] 配對問題

### ISSUE THREAD

**Issue by Avi-python** [csie-software-engineering/resonance-chatroom#92]
## 錯誤說明

貌似在配對成功之後，等待 node 就會被刪除，會有一個問題
有一邊 A 開始等待配對（getChatToUserId）進入等待 node，輪巡開始 / 另一邊 B 這時候也執行 getChatToUserId，但是他發現有人在等待，創建房間，就把 node 刪掉。
A 這時候輪尋執行 isWaiting，發現自己沒有在等待了，就執行 getChatToUserId 卻 get 不到東西，反而又再次進到
node。

## 預期結果

可以 get 到 peerId。

## 圖片或影片

![image](https://github.com/csie-software-engineering/resonance-chatroom/assets/62063088/302f9078-32d5-4e2e-b4eb-d0ecc5939059)

會 get 到 null

**Comment by garyellow** [comment]
我有開一個分支改了，可以rebase去用看看，等等應該會發pr

**Comment by Avi-python** [comment]
喔虧，可以配對了，沒有什麼問題

**Comment by garyellow** [comment]
要等 merge 再 close 餒XD

**Comment by garyellow** [comment]
沒問題的話可以幫忙 review & merge
