### ISSUE TITLE
[BUG] 不能 update user

### ISSUE THREAD

**Issue by Avi-python** [csie-software-engineering/resonance-chatroom#93]
## 錯誤說明

因為 User class 定義
isEnable 的修飾詞是 late final，以至於要 update User 的時候有一個 user.isEnable = true;，就報錯了。

## 如何重現

* 請在這裡說明錯誤該如何重現
* 描述哪裡需要改善

## 預期結果

* 該行為應該要長怎樣
* 調整成怎樣會更好

## 圖片或影片

![image](https://github.com/csie-software-engineering/resonance-chatroom/assets/62063088/08febd32-b6e2-47b6-b941-8291747b6a54)
![image](https://github.com/csie-software-engineering/resonance-chatroom/assets/62063088/9f1e291b-bcc8-409c-92ef-2b4ef2115d50)
![image](https://github.com/csie-software-engineering/resonance-chatroom/assets/62063088/bbb0c284-4d9e-4b5a-b338-8b512ac979b0)

## 關聯 ISSUE

* #50

**Comment by garyellow** [comment]
先把 final 拿掉應該就行了，我晚點檢查一波再弄一個pr
